#!/bin/bash

#PBS -l nodes=3:ppn=20,mem=700GB
#PBS -l walltime=100:00:00
#PBS -N abc_nbarxi
#PBS -M mjvakili@nyu.edu,chh327@nyu.edu
#PBS -m abe
#PBS -j oe
 
module load pyfof/gnu/0.1.2 
module load mpi4py/openmpi/intel/1.3.1

mpiexec \
    env LD_PRELOAD=${PYFOF_LIB}/python2.7/site-packages/pyfof.so \
    python -u /work/mv1003/ccppabc2/ccppabc/ccppabc/code/ccpp_abcpmc.py \
    30 1000 "nbarxi" abc
# leave a blank line at the end
 
